### ISSUE TITLE
[Feature] How to add read "permissions" to request on server side?

### ISSUE THREAD

**Issue by mixuala** [o1lab/xmysql#105]
My DB login is at the application level and I need to limit my GET queries with a `WHERE user_id==??` on the server side. Is there an easy hack to get this done?

**Comment by o1lab** [comment]
As is, there is no hack available. 

If you are proxying through your requests or something like that - may be you can append a _where query param to every GET request ?
```
_where=(user_id,eq,x)
```

**Comment by mixuala** [comment]
Well I suppose that’s the hack.
