### ISSUE TITLE
dynamic is not working

### ISSUE THREAD

**Issue by iahmedani** [o1lab/xmysql#11]
Hi team, 

first of all star to your efforts <3

I am sending an post request to dynamic api, but system is not response as required as it through 404 error,
ajax code:
`$(document).ready(function(){
	$.ajax({
	url: 'http://127.0.0.1:3000/dynamic',
	method: 'POST',
	data:{
        "query": "select * from ?? limit 20",
        "params": ["issuedetailsv3"]
    },
	success: function (data){
		console.log(data);
	},
	error : function (){
		console.log('this is an error');
			}
	})
});`
following errors,

> POST http://127.0.0.1:3000/dynamic 404 (Not Found)

> POST /dynamic 404 147 - 3.395 ms

Please provide dev environment versions of your system

node -v
v9.0.0
( xmysql requires node >= 7.6.0 )

npm -v
5.5.1
mysql --version
5.7.20
xmysql --version
0.2.0

- - -

Provide steps to reproduce this issue
or
Provide minimum code to reproduce this issue
or
HTTP request,response,error snapshot of this issue

- - -

Mark issue with suitable label if it is clear what this issue is.

**Comment by o1lab** [comment]
Hi, is the mysql server havng 'issuedetailsv3' is on your local system? /dynamic is available is available with local mysql server. Please paste your xmysql start options. 

If answers to above are yes. Then I might have some broken things along. Im currently travelling.. Will check in next couple of hours. Glad you liked it. Cheers

**Comment by o1lab** [comment]
Im unable to reproduce the issue. 

I am using postman to POST to http://localhost:3000/dynamic
And query executes fine. I have added few tests to cover /dynamic.

Note:
All dynamic requests can be POSTed by prepending anything meaningful while prototyping after /dynamic like below 

http://localhost:3000/dynamic/weeklyReport
http://localhost:3000/dynamic/user/update

**Comment by o1lab** [comment]
@iahmedani : feel free to open the issue if you are still facing the problem.

Please Note:
Use xmysql latest version to avail numerous APIs added over last week. (ugroupby, chart, bulk operations)
