### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by SAGOlab** [o1lab/xmysql#112]
**node -v: v13.6.0
npm -v: 6.14.3
mysql --version: 8.0.19
xmysql --version: xmysql@0.5.1**

- - -

issue steps provided:

cmd ran:
`xmysql -h IP  -o IP:PORT -u USERNAME -p PASSWORD -d DBNAME -n APPPORT`

error response:
`code: 'ER_NOT_SUPPORTED_AUTH_MODE',
  errno: 1251,
  sqlMessage: 'Client does not support authentication protocol requested by server; consider upgrading MySQL client',
  sqlState: '08004',
  fatal: true
`

- - -

the client of tool si mysql 5 compliance? in this case is possibile to update it to 8.0?

thanks

**Comment by o1lab** [comment]
https://github.com/mysqljs/mysql/issues/2046#issuecomment-396039909
