### ISSUE TITLE
POST urls give a 404 error

### ISSUE THREAD

**Issue by kamhlos** [o1lab/xmysql#113]
Hi, thanks for this!

The api urls produced (as shown on `curl localhost:34054`) are all GET, no POST's, no PUT, DELETE, etc.

node -v: 10.15.2
( xmysql requires node >= 7.6.0 )

npm -v: 5.8.0
mysql --version: mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
xmysql --version:undefined

- - -

Provide steps to reproduce this issue
$ curl --request POST   --data '{"username":"xyz","password":"xyz"}'   https://www.example.com/shop/customers

$ tail -f mysql_rest_api.log 
                                                            
          Database              :    shop
          Number of Tables      :    8
                                                            
          REST APIs Generated   :    108
                                                            
          Xmysql took           :    0.1 seconds
          API's base URL        :    localhost:34054

POST /api/customers 404 153 - 3.015 ms
- - -

Mark issue with suitable label if it is clear what this issue is.

**Comment by o1lab** [comment]
See your cli usage. May be you have enabled only get apis

**Comment by kamhlos** [comment]
that was it .. thanks
