### ISSUE TITLE
Add support for CORS headers

### ISSUE THREAD

**Issue by ferrybig** [o1lab/xmysql#12]
Please provide dev environment versions of your system

`node -v`: v9.2.0
( xmysql requires node >= 7.6.0 )

`npm -v`: 5.5.1
`mysql --version`: 5.7
`xmysql --version`: 0.4.0 (bug is also confirmed with version 0.0.2, the version I initially discovered this in)

- - -

Provide steps to reproduce this issue
0. Start xmysql on any database
1. Open your browser console
2. Request a page from xmysql (example: `await fetch('http://localhost:3000/')`)
3. Observe the request failing because of missing cors headers

- - -

Mark issue with suitable label if it is clear what this issue is.
Can't do this as only project members and higher have access to this feature, but I would mark this as "feature", "blocker"

**Comment by o1lab** [comment]
Sorry could not get back any earlier because of a terrible flu - this is a must feature as you have mentioned.

**Comment by markuman** [comment]
It's just

`npm install cors`


And 


```diff
diff --git a/index.js b/index.js
index 0b27c86..217fa69 100644
--- a/index.js
+++ b/index.js
@@ -1,5 +1,6 @@
 #! /usr/bin/env node
 
+const cors = require('cors')
 const morgan = require('morgan');
 const bodyParser = require('body-parser');
 const express = require('express');
@@ -16,6 +17,7 @@ cmdargs.handle(sqlConfig)
 
 /**************** START : setup express ****************/
 let app = express();
+app.use(cors())
 app.use(morgan('tiny'))
 app.use(bodyParser.json())
 app.use(bodyParser.urlencoded({
```


Another option is to handle cors headers by your reverse proxy, because I guess you won't run xmysql later on port 9000. But yeah, for developing, it's much easier when cors is included.

**Comment by o1lab** [comment]
@ferrybig : apologies. This was an easy fix which I couldn't get it in. Thank you for pointing it out. 

ps:
xmysql is undergoing interesting changes - very early days yet. Hope something good comes out.

**Comment by o1lab** [comment]
xmysql version 0.4.1 has the fix
