### ISSUE TITLE
Add _version or _health route

### ISSUE THREAD

**Issue by markuman** [o1lab/xmysql#14]
I'd like to include a health check into the docker file. E.g.

    HEALTHCHECK --interval=5s --timeout=3s \
      CMD curl --fail http://localhost:$PORT/_health || exit 1

So it would be nice to have a `/_health` route or something similar. The controller function should check if the connection to the mysql database is still alive. Or maybe a `_version` route, where `xmysql` responses with the connected `mysql` version. This can also be used for a health check.

What do you think?

**Comment by o1lab** [comment]
@markuman :  This is surely a good feature. Thank you for your suggestion.

For _health : Im thinking something like below

```javascript
{
   started_at: DATETIME
   health_status: status
   health_details: [ {cpu:cpu, memory: memory, heap:heap, other: suggest } ] 
   health_msg: "msg"
}   
```

For _version : something like below

```javascript
{
  xmysql_version:    
  mysql_version: 
}   
```

I will look up if there are any mysql query statements whose output be helpful too.

please suggest of what more would be helpful in each case or any existing package that will be helpful if you are aware of.

**Comment by o1lab** [comment]
@markuman - will pick this up after xmas as I am away.

**Comment by o1lab** [comment]
Below are in latest commit and in npm v0.4.2

```
http://localhost:3000/_health

{"process_uptime":6.733,"mysql_uptime":"3703"}
```

```
http://localhost:3000/_health?details=1

{"process_uptime":47.125,"mysql_uptime":"3743","os_total_memory":17179869184,"os_free_memory":2590732288,"os_load_average":[2.07177734375,2.03125,2.04638671875],"v8_heap_statistics":{"total_heap_size":24735744,"total_heap_size_executable":5242880,"total_physical_size":23714752,"total_available_size":1475416224,"used_heap_size":18431936,"heap_size_limit":1501560832,"malloced_memory":8192,"peak_malloced_memory":11065664,"does_zap_garbage":0}}
```


```
http://localhost:3000/_version

{"Xmysql":"0.4.1","mysql":"5.7.15","node":"8.2.1"}
```

**Comment by o1lab** [comment]
Some details can be found in documentation.
