### ISSUE TITLE
Listening on different IP

### ISSUE THREAD

**Issue by PhilippauxAdrien** [o1lab/xmysql#17]
Good morning,

I've tried to deploy xmysql on my server but I need to listen on a specific IP and port (ie. 127.2.X.X:8100).
I found the way to specify the portNumber but is there any other parameter to specify the IP to listen on ?

Regards,
Adrien

**Comment by o1lab** [comment]
I understand, you want to start Xmysql on a different ip interface of server.

**Comment by o1lab** [comment]
With option **-r** - various ip address on a server can be specified.

**Comment by PhilippauxAdrien** [comment]
Exactly but I finally found a way to do that by modifying the index.js file

**Comment by o1lab** [comment]
Good. 

I have added a new option '-r' for it in latest commit.

This will be there in next release to npm.

**Comment by o1lab** [comment]
Feature in npm v0.4.2
