### ISSUE TITLE
How to run in daemon mode?

### ISSUE THREAD

**Issue by pengyuwei** [o1lab/xmysql#18]
Please provide dev environment versions of your system

node -v
( xmysql requires node >= 7.6.0 )
v9.3.0

npm -v
5.5.1
mysql --version
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper
xmysql --version
0.4.1
- - -

I start xmysql in ubuntu ssh remote client, but when I close the terminal, the xmysql process will be exit.
So I want to run xmysql in daemon mode to let xmysql always run, but I found xmysql have no "--daemon" parameter.

So, how to run in daemon mode? Thank you.

**Comment by o1lab** [comment]
May be below link will help ?
https://stackoverflow.com/questions/4018154/how-do-i-run-a-node-js-app-as-a-background-service

Try and please let know which worked.

**Comment by pengyuwei** [comment]
I followed the method of this article to create an en file
`[Unit]
Description=en

[Service]
ExecStart="xmysql -h 127.0.0.1 -u en -p password -d en"
Restart=always
User=nobody
# Note RHEL/Fedora uses 'nobody', Debian/Ubuntu uses 'nogroup'
Group=nogroup
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/var/www/en/

[Install]
WantedBy=multi-user.target`

but I got a error:

`# systemctl start en
Failed to start en.service: Unit en.service is not loaded properly: Invalid argument.
See system logs and 'systemctl status en.service' for details.`

**Comment by o1lab** [comment]
I believe this issue is out of scope of this package. As suggested in stackoverflow - using some of packages (pm2 etc) - this problem could be solved.

@pengyuwei : please paste your solution when you have it working so that others could benefit.

**Comment by indatawetrust** [comment]
pm2 start --name "xmysql-api" xmysql -- -h localhost -u "" -p "" -d "" -n 5555
