### ISSUE TITLE
How to use https to call API

### ISSUE THREAD

**Issue by pengyuwei** [o1lab/xmysql#19]
I want to use https  call my API, but xmysql default is use http

**Comment by o1lab** [comment]
https with xmysql (and node) is nice to have but I kind of agree with suggestion made in top stackoverflow question that its better that nginx (or proxies or aws load balancers etc) handle ssl and route traffic to node server.

I am not an expert at ssl but I remember doing something similar with Kubernetes (or docker - I forget which) a couple of years ago where ssl traffic was routed to node port.

I will be closing the issue. However feel free to reopen the issue if you really find the need to have node handle ssl setup in production setup.
