### ISSUE TITLE
how did you own so many stars on this project in such a short time ?

### ISSUE THREAD

**Issue by downgoon** [o1lab/xmysql#2]
it is about 6 months ago that i wrote [autorest4db](https://github.com/downgoon/autorest4db) which is similar to ``xmysql`` in automatically generating RESTful api for databases. But it's only 3 stars i have gotten.  how did you own so many stars in such a short time ? awesome !

**Comment by sunwu51** [comment]
js is more lightweight than java :)

**Comment by o1lab** [comment]
@downgoon (you mean get stars ? :) - it was a surprise for me too. I had [submitted](https://news.ycombinator.com/item?id=15580914) a link to hacker news and that got picked up. 

Could you pls help post xmysql to [ cnode China or hacker news equivalent) if you have access to them. Thank you.

**Comment by freemember007** [comment]
a good name and good introduction.
