### ISSUE TITLE
SQL Syntax error when posting 

### ISSUE THREAD

**Issue by PhilippauxAdrien** [o1lab/xmysql#23]
Good morning, 

When I try to make a POST request on my Customer table to insert a row it doesn't work. 
I got a SQL syntax error : 

 "error": {
        "code": "ER_PARSE_ERROR",
        "errno": 1064,
        "sqlMessage": "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1",
        "sqlState": "42000",
        "index": 0,
        "sql": "INSERT INTO `customer` SET "
    }

Did somebody already had this issue ?

**Comment by o1lab** [comment]
@PhilippauxAdrien : pls paste your request body and output of 'describe customers' table from mysql interface.

It looks like there are no fields in insert statement. 

I've not tried this on mariadb.

**Comment by PhilippauxAdrien** [comment]
@o1lab  I just npm update and restart my server and now it works. 
I don't know why but anyway that should be my bad :)

Thanks anyway 👍

**Comment by o1lab** [comment]
Good to know. 

If possible run tests for xmysql on mariadb. 

First clone xmysql to a folder
```
git clone https://github.com/o1lab/xmysql
```

Login to mysql/mariadb shell

```
mysql> create database classicmodels
mysql> use classicmodels
mysql> source path_to/xmysql/tests/sample.sql
```

Install mocha if its not installed and run tests
```
$ npm install -g mocha
$ mocha tests/*.js --exit
```

Pls let us know results of tests - this would be very helpful.

Thank you,

**Comment by PhilippauxAdrien** [comment]
I ran the tests and it seems everything is good : 


 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

          Database              :    classicmodels
          Number of Tables      :    8

          REST APIs Generated   :    160

    √ GET /apj/v1/tables should PASS (48ms)
    √ GET /apj/v1/payments/count should PASS
    √ GET /apj/v1/offices/distinct?_fields=country should PASS
    √ GET /apj/v1/customers/describe should PASS
    √ GET /apj/v1/payments/103___JM555205 should PASS
    √ GET /apj/v1/customers should PASS
    √ GET /apj/v1/customers/103 should PASS
    √ GET /apj/v1/payments?_p=2 should PASS
    √ GET /apj/v1/payments?_p=2&_size=10 should PASS
    √ GET /apj/v1/offices?_sort=city should PASS
    √ GET /apj/v1/offices?_fields=officeCode,city should PASS
    √ GET /apj/v1/offices?_fields=officeCode,ity should PASS
    √ GET /apj/v1/offices?_fields=-territory,-addressLine2,-state should PASS
    √ GET /apj/v1/offices?_where=(((officeCode,in,1,2))~and(city,eq,boston)) should PASS
    √ GET /apj/v1/offices?_fields=-territory,-addressLine2,-state,-tate should PASS
    √ GET /apj/v1/offices?_sort=-city should PASS
    √ POST /api/productlines should PASS (135ms)
    √ POST /api/productlines/bulk should PASS (53ms)
    √ POST /api/productlines/bulk should PASS (86ms)
    √ GET /apj/v1/productlines/bulk should PASS
    √ DELETE /api/productlines/bulk should PASS (67ms)
    √ PUT /api/productlines should PASS (47ms)
    √ POST /dynamic should PASS
    √ POST /dynamic/abc should PASS
    √ POST /dynamic should PASS
    √ PATCH /api/productlines/Hyperloop should PASS (51ms)
    √ DELETE /api/customers/:id should PASS (41ms)
    √ GET /apj/v1/offices/1/employees should PASS
    √ GET /apj/v1/offices/1/employees?_where=(jobTitle,eq,Sales%20Rep) should PASS
    √ GET /apj/v1/payments?_where=(amount,gte,1000)~and(customerNumber,lte,120) should PASS
    √ GET /apj/v1/offices?_where=(city,like,~on~) should PASS
    √ GET /apj/v1/offices?_where=(city,like,san~) should PASS
    √ GET /apj/v1/offices?_where=(country,nlike,us~) should PASS
    √ GET /apj/v1/payments?_where=(amount,gte,1000)&_sort=-amount should PASS
    √ GET /apj/v1/payments?_where=(checkNumber,eq,JM555205)~or(checkNumber,eq,OM314933) should PASS
    √ GET /apj/v1/payments?_where=((checkNumber,eq,JM555205)~or(checkNumber,eq,OM314933)) should PASS
    √ GET /apj/v1/employees/1002/employees should PASS
    √ GET /apj/v1/productlines/trains/products should PASS
    √ GET /apj/v1/productlines/trains/products should PASS
    √ GET /apj/v1/employees/1165/customers should PASS
    √ GET /apj/v1/customers/103/orders should PASS
    √ GET /apj/v1/products/S10_1678/orderdetails should PASS
    √ GET /apj/v1/customers/103/payments should PASS
    √ GET /apj/v1/customers/groupby?_fields=city&_sort=city should PASS
    √ GET /apj/v1/offices/ugroupby?_fields=country should PASS
    √ GET /apj/v1/offices/ugroupby?_fields=country,city,state should PASS
    √ GET /apj/v1/offices/ugroupby?_fields=country,city should PASS
    √ GET /apj/v1/offices/ugroupby?_fields= should PASS
    √ GET /apj/v1/payments/chart?_fields=amount should PASS (38ms)
    √ GET /apj/v1/payments/chart?_fields=amount&min=0&max=131000&step=25000 should PASS
    √ GET /apj/v1/payments/autochart should PASS
    √ GET /apj/v1/payments?_where=(amount,bw,1000,5000) should PASS
    √ GET /apj/v1/payments/chart?_fields=amount&min=0&max=131000&step=25000&range=1 should PASS
    √ GET /apj/v1/payments/chart?_fields=amount&steparray=0,50000,100000,140000 should PASS
    √ GET /apj/v1/payments/chart?_fields=amount&steparray=0,50000,100000,140000&range=1 should PASS
    √ GET /apj/v1/payments/chart?_fields=amount&range=1 should PASS
    √ GET /apj/v1/offices/1/employees?_groupby=jobTitle&_having=(_count,gt,1) should PASS
    √ GET /apj/v1/offices/1/employees?_groupby=jobTitle should PASS
    √ GET /apj/v1/offices?_groupby=country should PASS
    √ GET /apj/v1/offices?_groupby=country&_sort=country should PASS
    √ GET /apj/v1/offices?_groupby=country&_sort=_count should PASS
    √ GET /apj/v1/offices?_groupby=country&_sort=-_count should PASS
    √ GET /apj/v1/offices/groupby?_fields=country&_having=(_count,gt,1) should PASS
    √ GET /apj/v1/offices?_groupby=country&_having=(_count,gt,1) should PASS
    √ GET /apj/v1/offices/groupby?_fields=country should PASS
    √ GET /apj/v1/offices/groupby?_fields=country,city&_sort=city,country should PASS
    √ GET /apj/v1/orders/aggregate?_fields=orderNumber,customerNumber should PASS
    √ GET /apj/v1/orders/aggregate should FAIL
    √ GET /apj/v1/orders/groupby should FAIL
    √ GET /apj/v1/xjoin?_join=pl.productlines,_j,pr.products&_on1=(pl.productline,eq,pr.productline) should PASS
    √ GET /apj/v1/xjoin?_join=pl.productlines,_j,pr.products&_on1=(pl.productline,eq,pr.productline)&_fields=pl.productline,pr.productName should PASS
    √ GET /apj/v1/xjoin?_join=pl.productlines,_j,pr.products&_on1=(pl.productline,eq,pr.productline)&_fields=pl.productline,pr.productName&_size=2 should PASS
    √ GET /apj/v1/payments/count?_where=(amount,gt,19000) should PASS
    √ GET /apj/v1/payments/chart?_fields=amount&steppair=0,50000,40000,100000 should PASS
    √ GET /apj/v1/xjoin?_join=pl.productlines,_j,pr.products&_on1=(pl.productline,eq,pr.productline)&_fields=pl.productline,pr.productName&_size=2&_where=(productName,like,1972~) should PASS
    √ /_health should PASS
    √ /_health?details=1 should PASS
    √ /_version should PASS
    √ where clause unit ?_where=(abc,eq,1234) should PASS
    √ where clause unit ?_where=(abc,ne,1234) should PASS
    √ where clause unit ?_where=(abc,lt,1234) should PASS
    √ where clause unit ?_where=(abc,lte,1234) should PASS
    √ where clause unit ?_where=(abc,gt,1234) should PASS
    √ where clause unit ?_where=(abc,gte,1234) should PASS
    √ where clause unit ?_where=abc,eq,1234) should FAIL
    √ where clause unit ?_where=(abc,eq,1234 should FAIL
    √ where clause unit ?_where=(abc,eq1234) should FAIL
    √ where clause unit ?_where=(abceq,1234) should FAIL
    √ where clause unit ?_where=(1,eq,1)(1,eq,2)~or should FAIL
    √ where clause unit ?_where=(1,eq,1)~or~or(1,eq,2)(1,eq,2) should FAIL
    √ where clause unit ?_where=(abc,eq,1)~or(b,eq,2) should PASS
    √ where clause unit ?_where=((a,eq,1)~and(b,eq,2))~or(c,eq,3) should PASS
    √ where clause unit ?_where=((a,eq,1)~and(b,eq,2))~xor(c,eq,3) should PASS
    √ where clause unit ?_where=(a,eq,1)~and((b,eq,2)~or(c,eq,3)) should PASS
    √ where clause unit ?_where=(a,in,1,2,3) should PASS
    √ where clause unit ?_where=(a,like,~1234) should PASS
    √ where clause unit ?_where=(a,like,~1234~) should PASS
    √ where clause unit ?_where=(a,is,null)~and(b,is,true)~and(c,is,false) should PASS


  98 passing (4s)`

**Comment by o1lab** [comment]
Thanks mate
