### ISSUE TITLE
While joining two tables if some columns have same name then I am not able to select all column names (Only all unique column names are displaying in the output).

### ISSUE THREAD

**Issue by shivsharma396** [o1lab/xmysql#24]
If I am using _fileds and trying to select columns which have the common name then also in the output only one column is displaying. Not getting the option to alias column name.
**Example**:
 _Table1_ : User(id, name, email, city_id) 
_Table2_:  City(id, name)
_query_: /api/xjoin?_join=u.user,_lj,c.city&_on1=(u.city_id,eq,c.id)&_fields=u.id,u.name,c.id,c.name
_Output_:
[{
id: 1,
name : "xxx"
},{
id : 2,
name : "yyy"
}]
_Expected Output_:
[{
id: 1,
name : "xxx",
id: 1,
name : "city1"
},{
id : 2,
name : "yyy",
id: 2,
name : "city2"
}]

**Comment by o1lab** [comment]
Having multiple keys with same name in an object wouldn't work.

Fixed Output will be in the lines of -

```
Expected Output:
[{
u_id: 1,
u_name : "xxx",
c_id: 1,
c_name : "city1"
},{
u_id : 2,
u_name : "yyy",
c_id: 2,
c_name : "city2"
}]
```

where alias for tables getting joined ti.e u and c will be prepended with _

**Comment by o1lab** [comment]
@shivsharma396 Commit [5a9b6f4](https://github.com/o1lab/xmysql/commit/5a9b6f4a5f136fcb0b2722a2772f9761f27e7c55) has the fix and this will go in next release of npm.

Query:
```
/api/xjoin?_join=u.user,_lj,c.city&_on1=(u.city_id,eq,c.id)&_fields=u.id,u.name,c.id,c.name
```
Response:
```
[{
u_id: 1,
u_name : "xxx",
c_id: 1,
c_name : "city1"
},{
u_id : 2,
u_name : "yyy",
c_id: 2,
c_name : "city2"
}]
```

With this commit, _fields query param will be mandatory wherein earlier all fields of tables in join were getting selected.

**Comment by o1lab** [comment]
Solution in 0.4.4
