### ISSUE TITLE
xmysql is not an command

### ISSUE THREAD

**Issue by SpringStudent** [o1lab/xmysql#3]
![image](https://user-images.githubusercontent.com/14833956/32257462-21818ee0-bef0-11e7-9b67-ff54d083413c.png)
Am i usage not right?

**Comment by sunwu51** [comment]
Did you add `-g`  in `npm install`
```
npm install -g xmysql
```
If you do,maybe you have not add the `$NODE_HOME`  to `$PATH`.

**Comment by SpringStudent** [comment]
i do have add $NODE_HOME to $PATH,here is my config 

![image](https://user-images.githubusercontent.com/14833956/32261018-a4d2ce92-bf06-11e7-88c6-e61790479d39.png)

![image](https://user-images.githubusercontent.com/14833956/32261051-e6839cea-bf06-11e7-96f7-88727dd73d1c.png)


![image](https://user-images.githubusercontent.com/14833956/32261048-dad5a91a-bf06-11e7-8f15-ccdf637c4931.png)

**Comment by sunwu51** [comment]
国人啊~`npm install -g`安装的位置即你指定的`NODE_PATH`，从你的安装指令最后一句输出看出`D:\nodejs\node_global\xmysql`已经产生了（windows下还会产生一个xmysql.cmd），你可以到这个目录下就能看到。

而至于为什么不能全局用这个指令，原因在于`D:\nodejs\node_global`这个路径不在全局`PATH`或者用户的`PATH`中，你在系统或者用户的环境变量的`PATH`中添加这个路径即可。

甚至直接到刚才那个目录下`./xmysql.cmd -h xxxxx -d xxx`运行

**Comment by SpringStudent** [comment]
好使了，但是报错。
![image](https://user-images.githubusercontent.com/14833956/32262268-a6ba2c16-bf0e-11e7-8f1f-0e18c18445dc.png)

**Comment by sunwu51** [comment]
这是因为你的nodejs版本太低了，这个项目的README第一行就说了`node>7.6.0`，你可以到官网下载最新的`8.x`版本的安装包，替换掉现在的（安装目录指向原来的进行替换），然后重新配下环境变量~

**Comment by SpringStudent** [comment]
好的，谢谢你

**Comment by o1lab** [comment]
早上好 😄 

Thank you @sunwu51 for suggesting an upgrade.

@SpringStudent : try using nvm if you want to use multiple versions of node on your system.

**Comment by SpringStudent** [comment]
get it ,thanks。
