### ISSUE TITLE
Getting xmysql to work on AWS lambda

### ISSUE THREAD

**Issue by bertyhell** [o1lab/xmysql#32]
I was able to get xmysql to work on AWS lambda. This is just some docs on the process to help others. (this issue can be closed)

Typescript code for index.ts:
```typescript
import * as bodyParser from 'body-parser';
import * as express from 'express';

const serverless = require('serverless-http');
import * as cors from 'cors';
import { APIGatewayEvent, Context } from 'aws-lambda';
import * as config from './util/env-config';
import { NextFunction, Request, Response } from 'express';
import { AutoBeheerderError } from './util/autobeheerder-error';

const mysql = require('mysql');
const Xapi = require('./node_modules/xmysql/lib/xapi.js');
const morgan = require('morgan');

const app = express();
let onXapiInitialized = new Promise<void>((resolve, reject) => {
  try {

    // /**************** START : setup express ****************/
    app.use(morgan('tiny'));
    app.use(cors());
    app.use(bodyParser.json());
    app.use(bodyParser.urlencoded({
      extended: true
    }));
    // /**************** END : setup express ****************/

    app.use((req: Request, res: Response, next: NextFunction) => {
      // You can add authentication here
      console.log('got request for: ' + req.url, req);
      next();
    });

    let mysqlConfig = {
      host: config.envConfig.mysql.host,
      port: 3306,
      database: config.envConfig.mysql.database,
      user: config.envConfig.mysql.user,
      password: config.envConfig.mysql.password,
      apiPrefix: '/',
      ipAddress: 'localhost',
      portNumber: 3000,
      ignoreTables: [],
      storageFolder: __dirname
    };

    let mysqlPool = mysql.createPool(mysqlConfig);

    let xapi = new Xapi(mysqlConfig, mysqlPool, app);

    xapi.init(async (err: any, results: any) => {
      app.listen(3000);
      resolve();
    });

  } catch (err) {
    reject(err);
  }
});

export function handler(event: APIGatewayEvent, context: Context, callback: Function) {
  onXapiInitialized.then(() => {
    serverless(app)(event, context, callback);
  });
}
```

AWS setup notes:
* The deploy uses serverless: https://serverless.com/framework/docs/getting-started/
* The lambda function is accessed through API Gateway and access the RDS (mysql) database
** Make sure you deploy your API Gateway setup otherwise it won't be accessible.
* The security setup:
** You need to put your lambda in a VPC
** The lambda role needs access to the VPC
** The RDS server has to be inside the VPC as well

Performance:
* Requests to the API Gateway resolve in ~ 90ms

**Comment by o1lab** [comment]
@bertyhell : could you please make a PR request under a folder examples/aws-lambda/* ?

**Comment by bertyhell** [comment]
Sure, here you go: https://github.com/o1lab/xmysql/pull/34

**Comment by GuillermoBlasco** [comment]
It would be great to add to the example documentation on how to configure the lambda with rds using connection pooling as described in this article https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/

How do xmysql manage connection pooling internally? Because two cascaded connection pools are a bad idea :D but the nature of lambda would make preferable to use a connection pool proxy instead of an in-app instance connection pool.

**Comment by o1lab** [comment]
hey @GuillermoBlasco : Please checkout [XgeneCloud](https://github.com/xgenecloud/xgenecloud) - we 've taken the learning from here in implementing XgeneCloud - it takes care of pooling.
