### ISSUE TITLE
Max page size is actually 99, not 100

### ISSUE THREAD

**Issue by jsneden** [o1lab/xmysql#33]
Please provide dev environment versions of your system

node -v = v9.4.0
( xmysql requires node >= 7.6.0 )

npm -v = 5.6.0
mysql --version = mysql  Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3
xmysql --version = 0.0.4

- - -
http://api.xyz.com/api/invitations?_size=100 returns 20 rows (incorrect)
http://api.xyz.com/api/invitations?_size=99 returns 54 rows (correct)
(please remove domain names after issue has been reproduced on your end)

Also note that it's strange behavior that when a requested page size goes over the system limit, then it simply reverts back to the default 20. Would be better if API would throw an error code to indicate something went wrong.
- - -

Mark issue with suitable label if it is clear what this issue is.

( edit: removed domain name )

**Comment by o1lab** [comment]
There were couple of issues surrounding _size. Have fixed them in latest commit.

The strange behaviour of defaulting to 20 for invalid _size has been changed to below:
when _size > 100 - defaults to 100
when _size <= 0  - defaults to 20

I think this is more inline of what can be expected - handling out of bound requests for _size would be good I felt without throwing up error.

- - - 

Latest npm version 0.4.5 has this fix.
