### ISSUE TITLE
Generate API documentation

### ISSUE THREAD

**Issue by rmdwirizki** [o1lab/xmysql#37]
It would be good if it can automatically generate some API documentation using swagger specification (swagger.json) **or** API Blueprint (\*.apib) **or** Postman (\*.postman_collection.json)

**Comment by majado2** [comment]
Thank you for this beautiful work and a great start .. To my understanding it is a combination of SQL and No SQL to reduce the load on the SERVER .
But my question did you think about  The rules of users are also of the right to view, edit or delete For one row or count rows in table 
and if there are requests dad need to hook (code) what is the way ?

**Comment by o1lab** [comment]
@majado2 : If I understand correctly, the question is about access control list (ACL) and hooks. Please refer to #26

**Comment by o1lab** [comment]
Currently, there is no plan of API documentation. If anybody has solutions or suggestions - feel free to reopen this.
