### ISSUE TITLE
Hide table column

### ISSUE THREAD

**Issue by DmACKGL** [o1lab/xmysql#38]
Is there any way to hide a specific column?

**Comment by o1lab** [comment]
While retrieving rows - we can exclude a column like below

`/api/tableName?_fields=-sensitiveColumn`

Here sensitiveColumn would be excluded

However, if I understand the question completely - hiding columns by default for a table is not possible. Something to be considered in ACL implementation of this.

**Comment by o1lab** [comment]
@DmACKGL feel free to reopen
