### ISSUE TITLE
How to extend this lib to support swagger UI.

### ISSUE THREAD

**Issue by mandadimuralidharreddy** [o1lab/xmysql#4]
If it possible to extend this lib to support swagger UI then it will be more easy access data.

**Comment by o1lab** [comment]
I don't know much about swagger internals. They use yaml spec to generate frontend (Im guessing) and backend. Is there a way to convert mysql schema to swagger/openapi spec easily ?

**Comment by o1lab** [comment]
Closing this as currently swagger ui is not in scope.
