### ISSUE TITLE
Issue when xmysql container startup is before mysql container startup

### ISSUE THREAD

**Issue by Dpvh** [o1lab/xmysql#43]
When using xmysql in a docker network(trough a docker compose), there is a chance xmysql gets spinned up before the related database container is ready.
If that happens it seems that only /tables works but actual requests trough the /api/ don't seem to work.
Only manually restarting the xmysql image seems to fix it.

I fixed it by adding a  health check to the docker compose.
Like so:

xmysql-report:
      image: "markuman/xmysql:0.4.2"
      expose:
          - "80"
      entrypoint: /bin/sh
      command: [ "-c", "cd /usr/src/app/ && node index.js --host DATABASE_HOST --password PASSWORD --database report --user root --apiPrefix /xmysql-report/api/ --portNumber 80 --ipAddress 0.0.0.0" ]
      depends_on:
        database-DATABASE:
          condition: service_healthy

database-DATABASE:
    image: "MYSQL-IMAGE"
    expose:
      - "3306"
    ports:
      - "33306:3306"
    environment:
      - "TZ=Europe/Amsterdam"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

but docker documentation recommends the software (xmysql in this case) should be more flexible in this situation, so no healthcheck would be needed.

**Comment by Dpvh** [comment]
E

**Comment by Dpvh** [comment]
Closed by accident, reopened

**Comment by o1lab** [comment]
@Dpvh : could you please make a PR request to readme docker documentation ?

**Comment by Dpvh** [comment]
@o1lab , as i've never made a PR before it might take some practice but i will look into this.

**Comment by pdme** [comment]
hi all, I created a PR for this: #49 

happy to hear feedback!

**Comment by o1lab** [comment]
@pdme : Thank you
