### ISSUE TITLE
Use MySQL functions with filtering

### ISSUE THREAD

**Issue by YanvegHD** [o1lab/xmysql#45]
Hello,

Can't we use functions in a GET url ?
I tried it but it doesn't give me the right results, here's an example : 

localhost:3000/api/payments?_where=(start_on,lte,CURDATE())~and(IFNULL(end_on,CURDATE()),gte,CURDATE())

Here, I want to use the IFNULL function and the CURDATE function, but it returns me something different that a raw mysql query.

I'm coding a react native app, I could use a JS function to avoid using 'CURDATE()' but not IFNULL(), of make another query to check if end_on is null or not :(

Thanks !

node version : 10.7.0
npm version : 6.4.0
xmysql version : 0.4.9

**Comment by o1lab** [comment]
No, SQL functions aren't supported in clauses

**Comment by o1lab** [comment]
/dynamic is only available in local : idea being, not to allow dyanmic/rogue queries on remote servers. 

As of now - I haven't thought to support functions as in the above example.

**Comment by YanvegHD** [comment]
Hmm ok, can you close the issue ?
