### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by Biuni** [o1lab/xmysql#5]
I have this error on my command line:
![cattura](https://user-images.githubusercontent.com/11752289/32275081-23b5539e-bf0a-11e7-815d-52d99558eced.JPG)
What's the problem? The database exist and the username and password of mysql are correct.

**Comment by Ryuzakix3** [comment]
I have the same issue.  Database Server ist correct, user and password also. Installed over npm (npm install -g xmysql)

**Comment by Biuni** [comment]
For each command i have the same problem.
![cattura2](https://user-images.githubusercontent.com/11752289/32275313-1703d03e-bf0b-11e7-957f-a947765e4890.JPG)

**Comment by o1lab** [comment]
xmysql requires node >= 7.6.0

upgrade your node 
or
use nvm if you want to use multiple versions of node on your system.

**Comment by o1lab** [comment]
Similar report in #3
