### ISSUE TITLE
Provide docker-compose setup

### ISSUE THREAD

**Issue by bvkatwijk** [o1lab/xmysql#54]
First of all, this is a great project!

Adding a docker-compose script has the following benefits:
- No longer requires users to have certain (versions of) packages installed (e.g. `npm` and `node`)
- Create a deterministic development/test environment
- Replace the manual steps currently needed for testing with a single command

Would you be interested in this? I've been working on this in a fork, I can create a PR if you think this will benefit your project.

**Comment by o1lab** [comment]
@bvkatwijk thank you for your initiative - please make the PR

Add the required documentation.

**Comment by o1lab** [comment]
Closing ( thanks to #55 PR from @bvkatwijk )
