### ISSUE TITLE
Wordpress xjoin

### ISSUE THREAD

**Issue by MyWay** [o1lab/xmysql#65]
I'm trying to join two wordpress tables unsuccesfully with this xjoin query: /xjoin?_join=pl.wp_posts,_j,pr.wp_postmeta&_on1=(pl.ID,eq,pr.post_id)&_fields=pl.ID,pr.post_id
but I keep getting error 404, any hint?

This should be equal to SQL join: SELECT pl.ID, pr.post_id FROM wp_posts as pl JOIN wp_postmeta as pr ON pl.ID = pr.post_id

**Comment by o1lab** [comment]
I have no idea about wordpress tables.

Does the query work fine on wp tables ? And are you doing this on wp cloud ?

If foreign keys exists in wp tables .. This api can be done as posts/post_id/posts_meta/id

**Comment by MyWay** [comment]
Yes, the SQL query works. I'm doing it on my own installation.

**Comment by MyWay** [comment]
I "solved" removing -a option to change /api (don't know if a bug, or a nginx proxy problem). Thank you.
