### ISSUE TITLE
Security? Auth(entication|orization)

### ISSUE THREAD

**Issue by leocavalcante** [o1lab/xmysql#7]
How to provide an ACL on how who can POST or GET and what it can GET?

**Comment by o1lab** [comment]
Currently, from documentation:
> When NOT to use ?
> If you are in need of a full blown MVC framework, ACL, Authorisation etc - Not this.

This started as a fun project whose scope was limited to hashing out apis from a mysql schema for quick prototyping or demoing or internal hacking. However, its early days now - can't promise either way about these features.

**Comment by markuman** [comment]
You can use a webserver (nginx, apache, lighttpd ...) for securing xmysql with basic auth and https.

**Comment by o1lab** [comment]
Feel free to reopen when auth will be handled - closing this as of now.
