### ISSUE TITLE
if my port != 3306,how to connect mysql

### ISSUE THREAD

**Issue by jamy-lei** [o1lab/xmysql#81]
Please provide dev environment versions of your system

node -v
( xmysql requires node >= 7.6.0 )

npm -v
mysql --version
xmysql --version

- - -

Provide steps to reproduce this issue
or
Provide minimum code to reproduce this issue
or
HTTP request,response,error snapshot of this issue

- - -

Mark issue with suitable label if it is clear what this issue is.

**Comment by o1lab** [comment]
@jamy-lei : see -n option 

https://github.com/o1lab/xmysql#command-line-options
