### ISSUE TITLE
readme images are stretched on mobile devices

### ISSUE THREAD

**Issue by DanielRuf** [o1lab/xmysql#90]
The images are stretched on mobile devicss. There might be a "height" value which is problematic.

**Comment by o1lab** [comment]
Which browser is it ? It has height. Yet appears good on chrome and android.

**Comment by DanielRuf** [comment]
Any browser. Try to emulate a mobile device.

**Comment by DanielRuf** [comment]
![Screenshot_20191117-180524](https://user-images.githubusercontent.com/827205/69010898-c255bd80-0964-11ea-81fb-2a624568e066.jpg)

I will probably provide a PR to fix this.
