### ISSUE TITLE
Problem with  JSON

### ISSUE THREAD

**Issue by yuanchuming** [o1lab/xmysql#98]
Please provide dev environment versions of your system

node -v
( xmysql requires node >= 7.6.0 )

npm -v
mysql --version
xmysql --version

- - -

Provide steps to reproduce this issue
or
Provide minimum code to reproduce this issue
or
HTTP request,response,error snapshot of this issue

- - -

Mark issue with suitable label if it is clear what this issue is.

**Comment by ans-4175** [comment]
Whats the problem if I may know?
